name: student_performance_analysis
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas~=0.23.4
  - matplotlib~=2.2.3
  - seaborn~=0.9.0
  - mpld3==0.5.10
  - pip:
    - -r ./src/requirements.txt  # 安装项目中requirements.txt里的其他依赖
