name: student_performance_analysis
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas>=1.0.0  # 更新 pandas 到与 Python 3.8 兼容的版本
  - matplotlib>=3.1.0  # 更新 matplotlib 到与 Python 3.8 兼容的版本
  - seaborn>=0.11.0  # 更新 seaborn 到与 Python 3.8 兼容的版本
  - pip  # 显式添加 pip 依赖项
  - pip:
    - mpld3  # 尝试安装最新版本的 mpld3，或者如果不存在则移除
    - -r ./src/requirements.txt  # 安装项目中requirements.txt里的其他依赖
