name: student_performance_analysis
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas>=1.5.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - pip
  - pip:
    - Flask==2.1.0
    - Jinja2==3.1.2
    - Werkzeug==2.2.3
    - numpy==1.24.0
    - scikit-learn==1.1.3
    - scipy==1.10.0
